mn_frontend:
    resource: "@MNFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

mn_useful:
    resource: "@MNUsefulBundle/Controller/"
    type:     annotation
    prefix:   /

mn_match:
    resource: "@MNMatchBundle/Controller/"
    type:     annotation
    prefix:   /

mn_player:
    resource: "@MNPlayerBundle/Controller/"
    type:     annotation
    prefix:   /

_imagine:
    resource: .
    type:     imagine

