<?php

namespace MN\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getLastGame(){
        $date = new \DateTime();
        $query = $this->getEntityManager()->createQueryBuilder('g')
            ->select('g')
            ->from('MNMatchBundle:Game', 'g')
            ->where('g.date < :game_date')
            ->setParameter('game_date', $date)
            ->orderBy('g.date', 'desc')
            ->setMaxResults(1)
            ->getQuery()
            ->getResult()
            ;
        return $query[0];
    }

    public function getNextGame(){
        $date = new \DateTime();
        $query = $this->getEntityManager()->createQueryBuilder('g')
            ->select('g')
            ->from('MNMatchBundle:Game', 'g')
            ->where('g.date >= :game_date')
            ->setParameter('game_date', $date)
            ->orderBy('g.date', 'asc')
            ->getQuery()
            ->setMaxResults(1)
            ->getResult()
            ;

        return $query[0];
    }
}
