<?php

namespace MN\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getLastGame(){
        return $this->getEntityManager()->createQueryBuilder('g')
            ->select('g')
            ->from('MNMatchBundle:Game', 'g')
            ->where('g.date < :game_date')
            ->setParameter('game_date', new \DateTime())
            ->orderBy('g.date', 'desc')
            ->getQuery()
            ->getSingleResult();
    }

    public function getNextGame(){
        return $this->getEntityManager()->createQueryBuilder('g')
            ->select('g')
            ->from('MNMatchBundle:Game', 'g')
            ->where('g.date >= :game_date')
            ->setParameter('game_date', new \DateTime())
            ->orderBy('g.date', 'asc')
            ->getQuery()
            ->getSingleResult();
    }
}
