<?php

namespace MN\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultTypeRepository extends EntityRepository
{
}
